### ISSUE TITLE
About the KLD curve

### ISSUE THREAD

**Issue by dongqian0206** [ysmiao/nvdm#2]
I ran the original code for NVDM and found that the kld loss curve decreased and then quickly increased. 

According to the ELBO, B = -KL[q(z|x) || p(z)] + E[p(x|z)]. Maximizing this bound is equivalent to minimizing KL[q(z|x) || p(z)] and maximizing E[p(x|z)]. The KLD curve should approach to zero, because KL[q(z|x) || p(z)] >= 0. 

The experimental result is strange.

**Comment by alexbie98** [comment]
I'm digging up a very old comment - but I believe in this case we don't want the the KLD to approach zero. In that case we would have that our variational posterior q(z|x) is distributed the same as our prior p(z), a Gaussian(0,1) - which would imply that regardless of the input document X we would be sampling from the same latent distribution.

**Comment by yilunzhao** [comment]
same question, could anyone help to explain it?
